# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

dump_dir: /tmp
name: "debug"
steps: 1000
probe_freq: 100
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    # fsdp_type: full_shard
    fsdp_type: no_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 1024
    n_layers: 8
    n_heads: 8

data:
    root_dir: /Volumes/main/rohitkg/data/raw_data/lingua_train_data
    sources:
        fineweb_edu_10bt: 100.0
    batch_size: 32
    prefetch_size: 64
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        name: bytes

profiling:
    run: true

checkpoint:
    path: /Volumes/main/linyuan/checkpoints/lingua/debug-demo/
    dump:
        every: 100
        keep: 100
    eval:
        every: 100
        keep: 1

logging:
    freq: 10
    mlflow:
        enabled: true
        tracking_uri: "databricks"  # defaults to ./mlruns
        run_name: "lingua_debug"

# eval:
#     generator:
#         max_tokens: 8192
#         dtype: bf16
#         temperature: 1.0
#         top_p: 0.95
#     harness:
#         tasks:
#             - hellaswag
#             - piqa
#             - task: nq_open
#               num_fewshot: 5
#     validation:
#         max_steps: 100
