# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path
dump_dir: /tmp/lingua_llama_1B
name: "debug_llama_1b"
steps: 100000
grad_acc_steps: 4
probe_freq: null
seed: 777

optim:
  lr: 1e-5
  weight_decay: 0.033
  warmup: 1000
  lr_min_ratio: 1.0 
  clip: 1.0
  scheduler: linear

distributed:
    fsdp_type: no_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 2048
    ffn_dim_multiplier: 1.5
    multiple_of: 256
    n_heads: 32
    n_kv_heads: 8
    n_layers: 32
    norm_eps: 1e-5
    rope_theta: 500000.0
    # dim: 2048
    # n_layers: 25
    # n_heads: 16

data:
    # root_dir: data/shuffled
    root_dir: /Volumes/main/rohitkg/data/raw_data/lingua_train_data
    sources:
        fineweb_edu_10bt: 100.0
    batch_size: 4
    prefetch_size: 32
    seq_len: 1024
    n_views: 2
    load_async: true
    tokenizer:
        name: bytes

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  path: /Volumes/main/linyuan/checkpoints/lingua/llama_2B_tubi/
  dump:
    every: 100
    keep: -1
  eval:
    every: 100
    keep: 3

logging:
    freq: 100
    mlflow:
        enabled: true
        tracking_uri: "databricks"  # defaults to ./mlruns
        run_name: "lingua_llama_1B_tubi"

# eval:
#     generator:
#         max_tokens: 8192
#         dtype: bf16
#         temperature: 1.0
#         top_p: 0.95
#     harness:
#         tasks:
#             - hellaswag
#             - piqa
#             - task: nq_open
#               num_fewshot: 5
#     validation:
#         max_steps: 100